$(document).ready(function(){
	$(".c2").hide();
	$("#news3-image2").hide();
	$("#news3-image3").hide();
	$("#news1-image2").hide();
	$("#news1-image3").hide();
	$("#news2-image2").hide();
	$("#news2-image3").hide();
	$("#news4-image2").hide();
	$("#news4-image3").hide();
	$(".news3-image1").mouseenter(function(){
		$("#news3-image1").show();
		$("#news3-image2").hide();
		$("#news3-image3").hide();
	});
	$(".news3-image2").mouseenter(function(){
		$("#news3-image2").show();
		$("#news3-image1").hide();
		$("#news3-image3").hide();
	});
	$(".news3-image3").mouseenter(function(){
		$("#news3-image3").show();
		$("#news3-image1").hide();
		$("#news3-image2").hide();
	});

	$(".news1-image1").mouseenter(function(){
		$("#news1-image1").show();
		$("#news1-image2").hide();
		$("#news1-image3").hide();
	});
	$(".news1-image2").mouseenter(function(){
		$("#news1-image2").show();
		$("#news1-image1").hide();
		$("#news1-image3").hide();
	});
	$(".news1-image3").mouseenter(function(){
		$("#news1-image3").show();
		$("#news1-image1").hide();
		$("#news1-image2").hide();
	});

	$(".news2-image1").mouseenter(function(){
		$("#news2-image1").show();
		$("#news2-image2").hide();
		$("#news2-image3").hide();
	});
	$(".news2-image2").mouseenter(function(){
		$("#news2-image2").show();
		$("#news2-image1").hide();
		$("#news2-image3").hide();
	});
	$(".news2-image3").mouseenter(function(){
		$("#news2-image3").show();
		$("#news2-image1").hide();
		$("#news2-image2").hide();
	});

	$(".news4-image1").mouseenter(function(){
		$("#news4-image1").show();
		$("#news4-image2").hide();
		$("#news4-image3").hide();
	});
	$(".news4-image2").mouseenter(function(){
		$("#news4-image2").show();
		$("#news4-image1").hide();
		$("#news4-image3").hide();
	});
	$(".news4-image3").mouseenter(function(){
		$("#news4-image3").show();
		$("#news4-image1").hide();
		$("#news4-image2").hide();
	});

	$("#x1").mouseenter(function(){
		$("#c1x1").hide();
		$("#c2x1").show();
	});
	$("#x1").mouseleave(function(){
		$("#c2x1").hide();
		$("#c1x1").show();
	});
	$("#x2").mouseenter(function(){
		$("#c1x2").hide();
		$("#c2x2").show();
	});
	$("#x2").mouseleave(function(){
		$("#c2x2").hide();
		$("#c1x2").show();
	});
	$("#x3").mouseenter(function(){
		$("#c1x3").hide();
		$("#c2x3").show();
	});
	$("#x3").mouseleave(function(){
		$("#c2x3").hide();
		$("#c1x3").show();
	});
	$("#x4").mouseenter(function(){
		$("#c1x4").hide();
		$("#c2x4").show();
	});
	$("#x4").mouseleave(function(){
		$("#c2x4").hide();
		$("#c1x4").show();
	});
	$("#x5").mouseenter(function(){
		$("#c1x5").hide();
		$("#c2x5").show();
	});
	$("#x5").mouseleave(function(){
		$("#c2x5").hide();
		$("#c1x5").show();
	});
	$("#x6").mouseenter(function(){
		$("#c1x6").hide();
		$("#c2x6").show();
	});
	$("#x6").mouseleave(function(){
		$("#c2x6").hide();
		$("#c1x6").show();
	});
	$("#x7").mouseenter(function(){
		$("#c1x7").hide();
		$("#c2x7").show();
	});
	$("#x7").mouseleave(function(){
		$("#c2x7").hide();
		$("#c1x7").show();
	});
	$("#x8").mouseenter(function(){
		$("#c1x8").hide();
		$("#c2x8").show();
	});
	$("#x8").mouseleave(function(){
		$("#c2x8").hide();
		$("#c1x8").show();
	});
});